### ISSUE TITLE
XML/Ada dependency cycle

### ISSUE THREAD

**Issue by Earnestly** [AdaCore/gprbuild#1]
Xmlada is required to build gprbuild, however xmlada requires gprbuild.  This dependency cycle has led to distributions each creating rather baroque and ugly build files for their xmlada package (E.g. [Debian](http://www.ada-france.org:8081/revision/browse/76e65b3b897bf04c492206c877004ff6fc125b6c/debian), [FreeBSD](https://www.freshports.org/commit.php?message_id=201506212335.t5LNZBsJ053647@svn.freebsd.org) and the [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xmlada)).

Please consider reducing external dependencies on gprbuild or fix dependency cycles by providing portable build systems that can be used to bootstrap said dependencies.

**Comment by t-14** [comment]
Hello,

AdaCore provides GNAT GPL distributions on a number of platforms that can be used to bootstrap the builds. The packages can be downloaded from [libre.adacore.com](libre.adacore.com) and they include gprbuild.

**Comment by Earnestly** [comment]
This doesn't solve the problem so I'm not sure why you're closing this issue.

**Comment by t-14** [comment]
I understand your point, but there is a reason for the circularity. As you have remarked, going without gprbuild results in "ugly and baroque build files" instead of a few simple build commands, which is why XML/Ada (and most our other projects) use gprbuild. On the other hand, XML/Ada is a critical gprbuild component since this is what the knowledge base is implemented in, so removing this dependency is not an option.

An alternative is to break the dependency cycle with a bootstrap, for which one can use a precompiled gprbuild from GNAT GPL distribution, providing a solution to the issue you raise.

**Comment by Earnestly** [comment]
A better solution here is to bite the bullet and create a well made and elegant Makefile (yes, it is possible but nobody has time to learn how make works) or another portable build system, even if it's using gnatmake and a shell script for XML/Ada. 

(I have personally tried and struggled to do [something reasonable](https://ptpb.pw/Nwt0/make); it doesn't work quite well enough yet but it can get me some of the way there.  It seems completely within reason but my lack of domain experience in Ada is hurting.  For a language propounding relability and correctness the build system and management of the language is bitterly disappointing and disempowering, culiminating in disinterest for an otherwise great language.)

Clearly you've had to create a compiled blob initially, why not use the same (internal?) mechanism here?

I think you (adacore) can certainly do a lot better than following the GPL in all but spirit.

**Comment by t-14** [comment]
"Well made and elegant Makefile"? This sounds like a GPR file to me ;)

As far as elegant Makefiles are concerned, I have yet to discover such a creature of legend, especially if the system is moderately large and you try to take different platforms and their various idiosyncrasies into account (note that your Makefile doesn't). It's precisely dissatisfaction with make as a build system felt by us and shared by our customers that led us to bite the bullet and develop gprbuild. It's quite empowering actually as far as build systems go.

**Comment by Earnestly** [comment]
This issue wasn't opened for advertising your products.

**Comment by t-14** [comment]
Well, following your remarks like "management of the language is bitterly disappointing and disempowering, culiminating in disinterest for an otherwise great language" and "I think you (adacore) can certainly do a lot better than following the GPL in all but spirit", I am in no doubt it wasn't opened for advertising our products, but I am becoming increasingly puzzled what was it opened for, exactly. I understand you like building programs with Makefiles, but don't you see the irony of peddling Makefiles to a project that is precisely an alternative?

**Comment by Earnestly** [comment]
This issue was opened exactly to address the deficiency of gprbuild not being buildable because no one can build its dependencies except for your company, and the bootstrapping is kept secret. Using a Makefile is merely one portable solution, I suggested others which you conveniently ignore in your replies. 

Yes you absolutely should provide necessary bootstrap code, however you wish to do it, so that XML/Ada can be built from source.

All you've done in this issue is throw a useless website at me which I'm pretty capable of finding.  A website in the past I've spent quite a long time on looking for methods to report bugs or view currently open issues, or even how to contribute to the project.

All I found was a faceless (not including the amusing stock images of smiling people, lol) "reports@adacore.com" address and promises of some "GNAT Tracker".

If I come across as aggressive, I'm sorry.  I'm frustrated that the two projects I've recently had to deal with, both proprietary-minded, have treated open source like a rubbish tip.  I've had issues closed simply because "I can't solve this right now" and "I'm not the developer", that's assuming they don't simply outright ignore everyone.

Now if you want irony, one of these projects are focused on code correctness and reliability (tis-interpreter).

As for Adacore, I'm surprised you're not acutely away of the trust issues involved in using pre-compiled binaries which are unverifiable or the efforts of reproducible builds, (cf. Ken Thompson's Trusting Trust and D. Wheeler's Fully Countering Trust through Diverse Double Compiling).

On that subject, you still haven't provided a direct link to this pre-compiled grpbuild which I asked for a few comments back (and please don't point to the 300+M bin tarballs).

**Comment by t-14** [comment]
Let's take a step back. You did come across as aggressive, I'm sorry for answering in kind. I understand your point, and we will see what we can do. I just want to repeat that providing a satisfactorily functioning and yet maintainable makefile of any complexity is very hard. What you perceived as my attempt to advertise gprbuild was in fact just statement of my conviction that it is a much, much friendlier build system, bootstrap issues notwithstanding. However this comes at a cost of considerable internal complexity that makes it problematic to reduce it down to a simple build script.

A few more comments:

> A website in the past I've spent quite a long time on looking for methods to report bugs or view currently open issues, or even how to contribute to the project.

This website is a downloads and information clearinghouse only, it is not intended for interaction (although there *is* a contact form you can use). It is with interaction in mind that we are in the process of moving projects to GitHub, but this transition started very recently (most our github projects including gprbuild are not even a month old, and some are still scheduled for transition).

> All I found was a faceless (not including the amusing stock images of smiling people, lol) "reports@adacore.com" address

Well, report@adacore.com (note, no "s") *is* the way we currently communicate. You can call it "faceless", but rather it's "many-faced" since a lot of people at AdaCore will receive it. Incidentally the smiling person in question is my colleague. You should be able to recognize him among AdaCore githubbers, but I'll pass along your compliment that he looks like a stock photo :-P

> As for Adacore, I'm surprised you're not acutely away of the trust issues involved in using pre-compiled binaries which are unverifiable or the efforts of reproducible builds

This is a very valid point but one that is not directly related to the issue of bootstrap. Do you mind opening a different issue? One way to address that is for the build system to produce a full executable list of build actions taken, so that the user can rerun it outside of the build system to verify the binary equivalence of the result or just to repeat the exact same build at a later time.

> On that subject, you still haven't provided a direct link to this pre-compiled grpbuild which I asked for a few comments back (and please don't point to the 300+M bin tarballs).

Sorry, but that's the way the package is currently distributed. It is certainly possible for us to consider distributing gprbuild separately e.g. for the soon-upcoming GPL 2016. Why don't you suggest it using the above-mentioned address?

**Comment by Earnestly** [comment]
Because the address is not public, like mailing lists.  I don't email internal companies.

**Comment by t-14** [comment]
Okay, but not providing feedback because you dislike the available feedback mechanism is the worst possible outcome, it ensures that if we ever converge it will be by chance.

Generally speaking there is also plenty of evidence to suggest that just because your feedback is seen by other users (and even +100'ed by other users) is no guarantee that it will be handled to your satisfaction, or in fact handled at all. A certain defect I had with a laptop of a popular brand, that got reported on said brand's support forum a month after that model appeared and accumulated thousands of "me too"s over two years without a single reply from the company in question comes to mind :) Ultimately no matter the feedback mechanism, it's the internal procedures that are meant to ensure the interaction and resolution occurs (or doesn't), and you can't control those. Personally I had mixed experience with both means of communication so can't really say that one works better than the other.

All I can say is that you *will* get a response from report@adacore.com, and as we don't have "support staff" it will necessarily be a response from a stakeholder. I make no promises it will be a satisfactory response however, but we do listen.

**Comment by Earnestly** [comment]
The public nature of it allows for other users to find the discussion and see the outcome or contribute to it.  This transparency really has nothing to do with the success or failure of that outcome.

This is why I'm replying here and not to some email address which I'm sure you're sincere about supporting.  It's frankly not good enough.  I hope your move to a more transparent system (such as github) will help with the future of the language instead of the current skunkworks development model.

Either way the point has been made at least for this issue and this discussion has gone onto too many tangents about how to run an open source project.  I'm not at all qualified to make suggestions however you could try contacting the awesome people at Collabora and becoming a client.

I've said what I'd like to see, and that is being able to bootstrap XML/Ada from source so that I can build gprbuild to use for the other Ada projects.

That's all.
