### ISSUE TITLE
bootstrap.sh fails with compilation error on OpenBSD Sparc64

### ISSUE THREAD

**Issue by romxero** [AdaCore/gprbuild#18]
I have an application that I am trying to port of to this platform. At the moment this is my issue:

egcc -c -I./ -I./src -I./gpr/src -I../xmlada.git/sax -I../xmlada.git/dom -I../xmlada.git/schema -I../xmlada.git/unicode -I../xmlada.git/input_sources -O -I- /home/romxero/Downloads/gprbuild-master/src/gprbuild-main.adb
gprbuild-main.adb:1888:10: "Try_Help" is undefined
gnatmake: "/home/romxero/Downloads/gprbuild-master/src/gprbuild-main.adb" compilation error

Gnat verstion is:

GNAT 4.9.3
Copyright 1996-2014, Free Software Foundation, Inc.

**Comment by pmderodat** [comment]
Hello @romxero and thank you for reporting this.

The error you get is due to the fact that the GPRbuild sources you try to compile depend on a version of the GNAT runtime that is more recent than the one your compiler (GNAT 4.9.3) has. Indeed, the Try_Help procedure was added in July 2014 (https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=316f8a9b2ab3bc228d662ccea7591c4afca76db6) whereas the GNAT 4.9 series started earlier the same year. What this means is that you need to upgrade your compiler in order to properly compile GPRbuild.

Our objective for this repository’s master branch is to support latest GCC release. Can you install a recent release (6.2 for instance, see https://gcc.gnu.org/gcc-6/) and try again?

**Comment by romxero** [comment]
Update!

gprbuild bootstrap was successful on OpenBSD 6.0/Sparc64 using gcc 6.2.0 in the ports tree. Issue closed.

**Comment by pmderodat** [comment]
Great, thank you for confirming!

**Comment by quentinsk** [comment]
> Update!
> 
> gprbuild bootstrap was successful on OpenBSD 6.0/Sparc64 using gcc 6.2.0 in the ports tree. Issue closed.

Hello, I know it is an old topic, but did you manage to compile gprbuild under OpenBSD 6.6/amd64 and gcc 8.3 with ada support , not the bootstrap that I manage to compile as well. I managed to modify some xml to get the correct gnat compiler recognized, but it seems to fail with finding some libraries. Tried on the most recent release of gprbuild. Even if an older version works, that's fine with me too.
