### ISSUE TITLE
Question about potential behavior change of Library_Options

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/gprbuild#27]
On a new system, I built the latest available gprbuild from source.  Since then I've repeatedly hit errors such as (for example):

```
unknown object file -L/usr/local
unknown object file -Wl,-rpath,/usr/local/somepath
```
These used to be recognized but apparently no longer are.
The problem is that many files attach LDFLAGS external variable to Library_Options and frequently LDFLAGS has -L and -R and -Wl flags set.

I don't remember ever hitting this before, so it is A) an intentional new behavior or B) a recently introduced bug or C) a side effect of something else?

To me it seems like a new bug but I'll reserve judgement.

**Comment by jrmarino** [comment]
I would think this is the comment where the behavior changed:
4d299c82f307d511b4578512bda854078086755e

**Comment by t-14** [comment]
> These used to be recognized but apparently no longer are.

Actually, these used to be unintentionally ignored, but no longer are. This is part of a fix to the fact that Library_Options weren't taken into account for static library projects (contrary to the doc).

> The problem is that many files attach LDFLAGS external variable to Library_Options and frequently LDFLAGS has -L and -R and -Wl flags set.

You should set differently Library_Options depending on whether you are building a static or a dynamic library. In static case, the only strings this attribute can contain is extra objects (as per documentation). In our experience, Library_Options should almost always be empty in the static case.

> I don't remember ever hitting this before, so it is A) an intentional new behavior or B) a recently introduced bug or C) a side effect of something else?

It's D) an intentional fix ;)

**Comment by jrmarino** [comment]
The problem is that it's not my software that is using LDFLAGS on library options.

I think the solution may be to back out the failure message in the referenced and let it operate as before.  The intentional fix seems to break more than it fixes (I'm not sure what it was trying to fix).

I would say to expect a lot of bug reports when the next gprbuild is released because I've seen this at least 5 times already, both with Adacore projects and non-Adacore projects, some very old.

It's going to be more pronounced when gcc's gnatmake stops supporting -P switch and gprbuild is the only game in town for project files.

**Comment by jrmarino** [comment]
to be clear, I'm going to test the removal of "Fail_Program
```
               else
 +                  Fail_Program
 +                    (null,
 +                     "unknown object file """ & Object_Path.all & """");
```
If that restores the behavior to allow gprbuild to build what it used to be able to build, I'm leaving the patch in for my users.

**Comment by jrmarino** [comment]
PPS - It was AWS 17.1 that prompted me to open the issue.
That's a flagship project by Adacore that gprbuild will fail to build if LDFLAGS are defined in the environment.

**Comment by t-14** [comment]
> The intentional fix seems to break more than it fixes (I'm not sure what it was trying to fix).

You don't seem to be reading what I wrote. Library_Options attribute was ignored before. It isn't ignored any more. If this fix "breaks" invalid projects, well, the projects need to be fixed, it's that simple.

> PPS - It was AWS 17.1 that prompted me to open the issue.

I don't follow. What has this got to do with AWS 17.1, which is a Pro version, and is supposed to be used in conjunction with gprbuild 17.1? Why are you not using the head of AWS github project where the issue has been fixed?

**Comment by t-14** [comment]
> If that restores the behavior to allow gprbuild to build what it used to be able to build, I'm leaving the patch in for my users.

No, this will not work, because you will be passing bogus switches to the archiver as a result. Please don't unfix things, fix invalid projects instead.

**Comment by jrmarino** [comment]
it's not simple.  I'm seeing a significant regression.  Projects that gprbuild used to be able to build now no longer can.  I think you can debate that this is the correct fix.  The linker ignore flags that aren't relevant (e.g. -L/-R on static libraries) so gprbuild is being "more correct" that that.

I understand your point (although I don't understand that Library_Options *never* had an effect if that's what you're saying).

Before fixing invalid projects (such as AWS 17.1 apparently) I'd first roll gprbuild back to a version that doesn't display the regression.  Others will likely do the same.  I'm just saying, be prepared to hear a lot about this if gprbuild has regressed in the name of "correctness".

**Comment by jrmarino** [comment]
if these really are invalid flags, can they be filtered out with a warning message instead?

**Comment by jrmarino** [comment]
Okay, my patch was successful.  I believe, in effect, these are simply filtering out the non-object files.   It's happening silently.  I wouldn't object to these being replace with visible non-fatal warnings.

```
--- src/gprbuild-post_compile.adb.orig  2016-12-23 15:59:49 UTC
+++ src/gprbuild-post_compile.adb
@@ -1794,11 +1794,7 @@ package body Gprbuild.Post_Compile is
                      end if;

                      if not OK then
-                        Error_Msg
-                          (Msg           => "unknown object file " &
-                                             Name_Buffer (1 .. Name_Len),
-                           Flag_Location => Library_Options.Location);
-                        Success := False;
+                        null;
                      end if;

                      List := Elem.Next;
```
and (fragment of bigger patch with unrelated hunks)
```
--- src/gprlib.adb.orig 2016-12-23 15:59:49 UTC
+++ src/gprlib.adb
@@ -1720,10 +1725,6 @@ procedure Gprlib is

                if Is_Regular_File (Object_Path.all) then
                   Object_Files.Append (Object_Path);
-               else
-                  Fail_Program
-                    (null,
-                     "unknown object file """ & Object_Path.all & """");
                end if;
             end;
          end loop;
```

**Comment by t-14** [comment]
> Projects that gprbuild used to be able to build now no longer can.

Sure, invalid projects that were not detected as such before now are, it is a normal outcome for a fix of this nature. Technical debt has accumulated and now needs to be paid. It's not a big deal, one just needs to add a selector if a project builds both static and dynamic libraries:

`
case Shared.Library_Type is
      when "static" =>
         null;
      when "relocatable" =>
         for Library_Options use ("-lwsock32", "-lws2_32");
end case
`
That's the way it's been done in AWS.

> The linker ignore flags that aren't relevant (e.g. -L/-R on static libraries) so gprbuild is being "more correct" that that.

We aren't talking of a linker but of an archiver (i.e. "ar"). And it won't ignore bogus switches, it will treat them as objects and will complain that there is no such file or directory. 

> I understand your point (although I don't understand that Library_Options never had an effect if that's what you're saying).

It didn't have an effect for static libraries. You have already identified the patch, you can just examine it and confirm for yourself.

> Before fixing invalid projects (such as AWS 17.1 apparently) I'd first roll gprbuild back to a version that doesn't display the regression.

I am still not clear why are we talking of AWS 17.1. We don't provide support for the use of AdaCore's Pro products via Github interface.

> if these really are invalid flags, can they be filtered out with a warning message instead?

That would be wrong, since as a result the library will be built without potentially critical objects (which is what your change does; you are just locking in the technical debt). And we can't distinguish objects and flags, since there is no difference between a flag and a file name.

**Comment by jrmarino** [comment]
I'm not asking for support of AWS 17.1.  It's been available for GCC FSF builds for months.  The point was release 17.1 fails to build with the latest gprbuild (without my patches).

> That would be wrong, since as a result the library will be built without potentially critical objects (which is what your change does; you are just locking in the technical debt). And we can't distinguish objects and flags, since there is no difference between a flag and a file name.

I'm not sure we are communicating.  The patches I showed don't pass on the bad flags.   They just ignore them, so they never get to AR.  The proof is in the pudding.  I just found 3 "bad" projects that gprbuild wouldn't build and after my patches it built them fine.  There was no errors from ar.

I thought my suggestion was a good one.  Keep a version of my patch but instead of a fatal error, just put a warning so that A) the developer sees the issue and B) you don't incur an unnecessary regression.
All my patches did were to remove unnecessary fatal errors, but they lack warning emissions.

**Comment by t-14** [comment]
> I'm not sure we are communicating. The patches I showed don't pass on the bad flags. They just ignore them, so they never get to AR.

Now imagine what will happen if the library should include a foreign object, which is unavailable for some reason. What your patch will do is silently ignore this situation (or ignore it with a warning if we follow your suggestion, doesn't change things much since nobody looks at warnings). And you will get an incomplete library as a result.

**Comment by jrmarino** [comment]
well, I can tell you people do look at warnings.  We have build logs and especially with gprbuild, every successful compilation is nice and neat, so every warning is jarring on a log.

Now, admittedly my knowledge of what is going on in the area I patched is low, but it appears that you're verifying the existence of an object file and only when that passes do you add that file to a container.  Presumably it's the contents of that contain that is sent to AR.  I'm not seeing how I get an "incomplete library" if an invalid flag is filtered out.  Can you help me get from point A to point B?  because right now I'm not seeing any measurable negative to what I've done (other than impede the correct fix from occurring)

**Comment by t-14** [comment]
"Nobody looks at warnings" was a polemic exaggeration of course, but warnings do get missed.

> Can you help me get from point A to point B?

We start with some string. We check if it exists as a file name. If it does, we add it to ar command line. If it doesn't, we have a conundrum: it can either be an invalid switch because user project didn't properly segregate static and dynamic libraries - in this case ignoring it is fine; or it can be an object file that the user meant to obtain out-of-build but didn't obtain for some reason (e.g. typo, packaging or CM issue, etc) - in this case ignoring it is not fine. We can't tell in which case are we, so we err on the side of caution.

**Comment by jrmarino** [comment]
Okay, thanks, I understand your point now.

I agree that we do not want to get into parsing the unknown string to try to figure out if it's a flag or not because there's no foolproof way (although you could guess right 90+% of the time I would think).
Personally I would still prefer an overt warning that would be logged but continue as if it's a flag.

You're point of view is that *I* am the developer of the bad project file and I should just fix it.  In reality, I'm just building other people's projects which used to work but now suddenly doesn't.  And having to patch other people's project files to remove the regression isn't appealing.   I would rather provide the author the log of the errors and ask him to fix it (with suggestions or a patch even).  That's where I am coming from and I doubt I am alone in this use case.  If it were just me and my bad project files, I would 100% agree with your technical debt POV.

**Comment by t-14** [comment]
I have to say though, looking closely at the timeline, I am not sure why would you have any issues with AWS. I thought we needed to fix it for this issue, but it doesn't look so, its project correctly sets Library_Options only for the dynamic case. Plus, we had put this change back in Sep 2016, long before we started on the release, so we couldn't have missed it. And indeed I can't reproduce it.

Is there anything special about your build procedure or environment? Maybe we are barking up the wrong tree and there's something we missed?

**Comment by jrmarino** [comment]
well, I'd have to roll back the change to gprbuild to reproduce it.  It was pretty far into the build before it happened, pretty much at the end.  Obviously it builds now with a patched gprbuild.  AWS was just the last project that failed; I saw it at least 3 separate times earlier so it was just the straw that caused me to ask the question.

For sure it's a combination of the build settings and dependencies.  I am confident in the build procedure and environment.  They are "clean" reproducible environments that are constructed for each build reproducibly and identically.  I've used the technique for years.

anyway, if I really, really wanted too I could go back and reproduce the failure but AWS was never my focus; it was just something I mentioned.

**Comment by jrmarino** [comment]
if I alter the patch on GPRBuild to emit warnings, I would see it as well.

**Comment by jrmarino** [comment]
Okay, I modified GPRBUILD to emit errors and determined the error is actually in the templates_parser (still release 17.1).
```
Build Libraries
   [gprlib]       templates_parser.lexch
WARNING: unknown object "/construction/aws/aws-17.1/templates_parser//-L/raven/lib"
WARNING: unknown object "/construction/aws/aws-17.1/templates_parser//-Wl,-rpath,/raven/lib"
WARNING: unknown object "/construction/aws/aws-17.1/templates_parser//-Wl,-rpath=/raven/lib"
   [archive]      libtemplates_parser.a
   [index]        libtemplates_parser.a
```

**Comment by t-14** [comment]
> Okay, I modified GPRBUILD to emit errors and determined the error is actually in the templates_parser

Ah-ha! Thanks for the heads up. I was initially confused why LDFLAGS would make a difference, but I can see that it does make a difference for templates_parser. Looks like we aren't setting it ourselves, so have missed it. Will fix.

I am still a bit puzzled about your mention of aws 17.1 at FSF, to the best of my knowledge the only thing we do is maintain aws/templates_parser at Github. Can you point me towards the place you got it from?

**Comment by jrmarino** [comment]
AWS is on github: https://github.com/AdaCore/aws
It's even got a tag: https://github.com/AdaCore/aws/releases
However, now I see that 17.2 has been released. :)

**Comment by jrmarino** [comment]
Yes, that's what I'm using.
On github, if something is "tagged", that creates a release.  So it appears to viewers that 17.2 has been tagged.  If it's a working version, the tag should be called something to indicate that, e.g. 17.2-beta1
I will not be using master.  Limiting to actual releases is the conservative approach.

Anyway, GCC FSF 6.3 builds aws just fine.

**Comment by t-14** [comment]
I understand this may be confusing, but that's not how we produce releases at AdaCore. Internally for us release is a branch, not a single tag. The actual revision on a branch that is used for source packaging is tracked by our own continuous integration system, not by git tags. Because reasons, not particularly relevant for this thread. The important thing is that it is not compatible with Github's notion of a release and both 17.1 and 17.2 tags in aws are bogus and don't correspond to anything in particular (i.e. there has never been an AdaCore's release that used 17.1 tag, and when 17.2 is out it won't use 17.2 tag either - it's a tag from February, and we didn't even finalize the 17.2 source set yet, need I say more).

> I will not be using master. Limiting to actual releases is the conservative approach.

Ok, your call, just as long as you realize that this tag means nothing at all to us ;) So what are you using to build gprbuild then? It has no releases in Github sense.

**Comment by jrmarino** [comment]
Well, would adacore consider making a special tag for actual releases?
Or, for example, on the annual release (which must be coming up soon), tag the actual commit used for the release.   I know what you are saying: ignore the tag, pick a branch, and use the top commit on that branch.  However, it would be nice if commit representing actual releases were highlighted with a tag.

As for gprbuild, I just picked the top commit at the time because, as you said, there was no release at all.

**Comment by t-14** [comment]
> Well, would adacore consider making a special tag for actual releases?

I've started thinking about that too. It is not straightforward since the moment of release production is controlled by release engineers and not by project managers, but probably _ex post facto_ we should be able to tag a revision that produced the release indeed. I'll pass it along. I agree the current situation is weird for github users.

> As for gprbuild, I just picked the top commit at the time because, as you said, there was no release at all.

Ok. You can also pick the top commit of the active release branch to be quite close to what we'll consider a release. Though it wouldn't have helped in this case since the patch was pushed quite a long time ago.

**Comment by jrmarino** [comment]
Thanks for considering back-tagging.  It would definitively help.
