### ISSUE TITLE
Builder’Default_Switches ("c++")

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gprbuild#40]
With this project file
```
project Main is
   for Languages use ("ada", "c++");
   for Main use ("main.cpp");
   package Builder is
      for Default_Switches ("ada") use ("-g");
      for Default_Switches ("c++") use ("-g");                       -- <<< line 6
   end Builder;
   package Binder is
      for Default_Switches ("ada") use ("-E");
   end Binder;
end Main;
```
gprbuild says
```
$ gprbuild
using project file main.gpr
main.gpr:6:41: "-g" is not a builder switch. Consider moving it to Global_Compilation_Switches.
gprbuild: *** illegal switch "-g"
```
I’ve been happily using `Builder’Default_Switches ("ada")` for ever. Why the inconsistency?

**Comment by simonjwright** [comment]
I also used to have
```
   for Default_Switches ("ada") use
        (
         "-g",
         "-O0",
         "-ffunction-sections",
         "-fdata-sections",
         "--create-map-file"
        );
```
and now gprbuild complains similarly about `-ffunction-sections`.

At least it’s clear why - `gprbuild --help` doesn’t permit `-ffunction-sections`.

**Comment by t-14** [comment]
Hi Simon,

Documentation [says](http://docs.adacore.com/gprbuild-docs/html/gprbuild_ug/building_with_gprbuild.html#switches),

> Switches that are accepted for compatibility with gnatmake, either on the command line **or in the Builder Ada switches** in the main project file: (...list of switches...)
> These switches are passed to the Ada compiler.

The previous behavior was not consistent with this: all unrecognized switches in package Builder were passed to respective compilers. This was fixed by 56eee93. We decided we do want to fix this, since this complicated investigation when a typo was made in the builder switch (which caused it to be silently forwarded to the compiler with unexpected effects).

You need to correct your project by moving your switch to package Compiler.

**Comment by simonjwright** [comment]
I do agree that the behaviour is consistent with the documentation; however, I wouldn’t have raised this issue if the behaviour had been ~~reasonable~~obviously correct!
What about a warning when the switches that are accepted for compatibility with gnatmake, but only for Ada, are present?

>You need to correct your project by moving your switch to package Compiler.

I used `Builder’Global_Compilation_Switches`.

**Comment by t-14** [comment]
> What about a warning when the switches that are accepted for compatibility with gnatmake, but only for Ada, are present?

I think it's too corner-case to justify adding code to warn about it.

> I used Builder'Global_Compilation_Switches

Indeed, that should work too.
