### ISSUE TITLE
Project options missed if called from aggregate project

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gprbuild#48]
I have a plain project which I call from an aggregate project so as to set some options (scenario variables). The plain project (`plain.gpr` in the attached demo) specifies `Create_Missing_Dirs`, and `Builder` specifies `--create-map-file` (`Linker` uses `Map_File_Options` to specify where to put the map file, or else it ends up in the `Object_Dir`, how annoying is _that_!).

Building with `plain.gpr`, all works fine (NB, the `Map_File_Options` are set up for macOS, see alternative for GNU ld).

Building with `agg.gpr`,
* `Create_Missing_Dirs` is ignored (but the command line `-p` isn’t)
* `--create-map-file` is ignored.

[aggregate-problem.zip](https://github.com/AdaCore/gprbuild/files/2364271/aggregate-problem.zip)

**Comment by t-14** [comment]
This is expected and (mostly) documented. The doc says:

> For projects that are built through the aggregate mechanism, the package Builder is ignored [...]

This applies explicitly to your second case, but also implicitly to your first case because Create_Missing_Dirs is also a builder-specific instruction and so also gets deactivated by aggregation.

**Comment by simonjwright** [comment]
I don’t really follow the argument in the documentation. Would have expected an aggregated project’s options to override those in the aggregate project; especially if the aggregate project doesn’t even _have_ a package Builder! I find the documentation really confusing.

Not clear what you mean by 'builder-specific instruction', since Create_Missing_Dirs appears at project level. My problem also arises with Target and Runtime; what happens if I have a multi-computer aggregate with different builds for different targets?

Create_Missing_Dirs doesn’t appear to be defined in the docs (at http://docs.adacore.com/live/wave/gprbuild/html/gprbuild_ug/gprbuild_ug.html)

**Comment by t-14** [comment]
> Would have expected an aggregated project’s options to override those in the aggregate project

No, it's the other way around - aggregate overrides the aggregated. If you need your projects to have distinct builder instructions - aggregate projects are probably not for you.

> especially if the aggregate project doesn’t even have a package Builder

This just means that default values are used.

> Not clear what you mean by 'builder-specific instruction', since Create_Missing_Dirs appears at project level.

Sorry, the answer for this one is a bit different than the one I provided (although it wouldn't make practical difference for you): this attribute is only taken into account for the main project. So if you use an aggregate project - that's your main.

> My problem also arises with Target and Runtime; what happens if I have a multi-computer aggregate with different builds for different targets?

They'll be ignored. As stated in the manual, Target and Runtime are only taken into account in the main project. So again if you use an aggregate project - that's your main. But this is not specific to aggregate projects - if you _import_ a project that defines Target rather than aggregate it, - it will also be ignored.

> Create_Missing_Dirs doesn’t appear to be defined in the docs

Indeed, looks to be the case. We will add it.

**Comment by simonjwright** [comment]
>Would have expected an aggregated project’s options to override those in the aggregate project
>>No, it's the other way around - aggregate overrides the aggregated.

Weird

>>If you need your projects to have distinct builder instructions - aggregate projects are probably not for you.

Oh well, back to Makefiles and Emacs ada-mode project files.

Thanks for your time.
