### ISSUE TITLE
config.sub is 15 years old (!)

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/gprbuild#7]
First ten lines of config.sub:
```
#! /bin/sh
# Configuration validation subroutine script.
#   Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
#   Free Software Foundation, Inc.

timestamp='2001-09-07'

# This file is (in principle) common to ALL GNU software.
# The presence of a machine in this file suggests that SOME GNU software
# can handle that machine.  It does not imply ALL GNU software can.
```

result:
```
checking build system type... Invalid configuration `x86_64-unknown-dragonfly4.5': system `dragonfly4.5' not recognized
configure: error: /bin/sh ./config.sub x86_64-unknown-dragonfly4.5 failed
```

How does using a 15 year old version of config.sub even happen?
I believe there is a reference version of config.sub easily available, but at least steal the latest version from the current binutils or gcc if all else fails.

(guess.sub is affected too)

**Comment by briot** [comment]
Sorry I have to ask: how does being aggressive help resolve technical issues ?

The real question here is how come this version works on all the systems we test (and we run builds on more than 50 different systems -- not machines, systems), but not on yours ?

Here, I would suggest you test with a newer version of config.sub, and then make a pull request. That's what github is about.  We might or not do the upgrade, that will depend on several factors but at least it has more chances of happening if you submit patches. Thanks in advance !

**Comment by jrmarino** [comment]
Briot, it's not aggressive.  If anything it is astonishment.
You have a 15 year old config.sub in place.  How can you defend that in any way?
Why does it work?  Because you are using systems that are on that list from 2001.  Nothing newer is there.  DragonFly came into existence in 2004.

Why are you telling me to fix something where the solution is obvious?

Bonus answer: Why hasn't it come up before?  Because our build system replaces config.sub with the latest automatically. I've never built out of the box before.  I found it now because I'm following the exact instructions.

Are you seriously suggesting that a config.sub from is a good thing?
What's the point of asking me why it works on what you test it on?  Surely you already know the answer?

**Comment by briot** [comment]
Just because "it works" as is on all our systems, so there is exactly no reason to change. We have quite a lot of experience on updating one of these scripts and suddenly some obscure platforms stops working fine because some name has changed. So there is definitely nothing trivial updating those scripts in general, you need good testing.

I am glad to know you know what we compile on better than we do. Of course, Windows 10 was already released in 2001, as every one knows.

To be clear again: nothing will happen here unless you take the trouble of submitting a pull request. 
Your company (since this doesn't seem to be a side project) is using an unsupported and free product. Don't complain when things don't work, just contribute fixes...

**Comment by jrmarino** [comment]
oh geez.  I suspected you guys didn't really get this whole github thing.
Yes, it's nice if somebody contributes a patch.

However, I just did you a huge service without giving you a patch.  I alerted you to an absurdly obsolete script.  Now you know.  And for your information, thousands of projects use config.sub and they use the latest.  The chances of breakage due to updating it is extremely small and of course it could be reverted.

Open source is not just free labour.

Aside:
No, this is not a company thing.  I am not using this product "for free" in a commercial sense even though I would be entitled to do so.

You're welcome for the free observation on a deficiency on your product.  I will probably continue to open issue about problems I find and I will not charge any money for this service.

**Comment by Nikokrock** [comment]
Hi,

Thanks for your report,

Please next time, don't start your report with "How does using a 15 year old
version of config.sub even happen?". This can happen because DragonBSD is not
something we support officially and this was never an issue for us with the
set of native systems we are testing: FreeBSD, Windows, Linux, Solaris, MacOS,
... We also tend to be very conservative as for each of them we need to support
both very old and newest versions.

The update of config.guess and config.sub is now under review. Once we are
sure that it passes all our internal QA procedure the change will be pushed
into Github.

--
Nicolas

**Comment by jrmarino** [comment]
Thanks.  Can the review be extended to any project using autotools?

**Comment by Nikokrock** [comment]
I can, but I don't have the time right now. If you have specific list in mind maybe you can just submit the update yourself to speed up the process. Will do the review. Or just give me the list of project you need and I will found some time soon to do it.

Thanks in advance

**Comment by jrmarino** [comment]
ok nico.  I apologize for my opening tone and will try to improve this in the future.  Thanks for looking at it despite how I started the conversation.

**Comment by Nikokrock** [comment]
You are welcome,

Written message and the perceived tone is always a tricky beast ;-)
